baseURL = 'https://perprompt.com/'
languageCode = 'en-us'
title = 'Per Prompt - Weekly LLV, GPT, AI Digests'
subtitle = 'Weekly digest of interesting news and tool about LLM, GPT and AI.'
theme = 'terminal'
keywords = 'llm,gpt,chatgpt,ai,tech'
enableRobotsTXT = true
enableEmoji = true

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 0
  showLanguageSelector = false
  fullWidthTheme = true
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  favicon = "favicon.ico"
  readingTime = true
  images = ['logo.png']
  subtitle = 'Weekly digest of interesting news and tool about LLM, GPT & AI'

[params.giscus]
  repo = "momentmaker/perprompt"
  repoID = "R_kgDOJXluAQ"
  category = "Posts"
  categoryID = "DIC_kwDOJXluAc4CV6Ac"
  mapping = "og:title"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "dark"
  lang = "en"
  loading = "lazy"

[params.twitter]
  creator = "per_prompt"
  site = "per_prompt"
  image = "https://perprompt.com/logo.png"

[languages]
  [languages.en]
    languageName = "English"
    menuMore = "Show"
    readMore = "Read"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "/_"
      logoHomeLink = "/"
